# Generated by Django 3.2 on 2023-06-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('hall_number', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('modified_time', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'hall',
                'verbose_name_plural': 'halls',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True, verbose_name='table_number')),
                ('table_capacity', models.IntegerField(default=4)),
                ('price', models.IntegerField(verbose_name='price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('modified_time', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'table',
                'verbose_name_plural': 'tables',
            },
        ),
    ]
