# Generated by Django 3.2 on 2023-06-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_hall_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='upc',
            field=models.IntegerField(default=101, unique=True),
            preserve_default=False,
        ),
    ]
