# Generated by Django 3.2 on 2023-06-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='table',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
    ]
